services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

  web:
    build: .
    container_name: web
    command: >
      gunicorn project.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --threads 2
      --timeout 60
      --graceful-timeout 30
      --access-logfile /app/logs/gunicorn_access.log
      --error-logfile /app/logs/gunicorn_error.log
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs  

    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  celery:
    build: .
    container_name: celery
    entrypoint: /app/entrypoint.worker.sh
    command: celery -A project worker -l info --logfile=/app/logs/celery_worker.log

    volumes:
      - logs_volume:/app/logs  

    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped
    
    networks:
      - backend

  celery-beat:
    build: .
    container_name: celery-beat
    entrypoint: /app/entrypoint.worker.sh
    command: celery -A project beat -l info --logfile=/app/logs/celery_beat.log
    volumes:
      - logs_volume:/app/logs  

    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
