# Generated by Django 5.2.8 on 2026-01-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب المستخدم ', 'verbose_name_plural': 'حسابات المستخدمين'},
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
