# Generated by Django 5.2.8 on 2025-12-31 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة عميل',
                'verbose_name_plural': 'رسائل العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرد')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('customer_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.customermessage', verbose_name='الرسالة الأصلية')),
            ],
            options={
                'verbose_name': 'رد',
                'verbose_name_plural': 'الردود',
                'ordering': ['created_at'],
            },
        ),
    ]
