# Generated by Django 5.2.15 on 2026-08-08 12:26

import utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='اسم السلايد')),
                ('image_width', models.PositiveIntegerField(default=0, editable=False)),
                ('image_height', models.PositiveIntegerField(default=0, editable=False)),
                ('image', models.ImageField(height_field='image_height', upload_to='home/slides/', verbose_name='الصورة', width_field='image_width')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='النص البديل للصورة')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سلايد الصفحة الرئيسية',
                'verbose_name_plural': 'سلايدر الصفحة الرئيسية',
                'ordering': ['order', 'id'],
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
    ]
