# Generated by Django 5.2.8 on 2026-01-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سلة التسوق', 'verbose_name_plural': 'سلات التسوق'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'تفاصيل السلة', 'verbose_name_plural': 'تفاصيل السلات '},
        ),
    ]
