# Generated by Django 5.2.8 on 2025-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size_name',
            field=models.CharField(blank=True, help_text='اسم الطول/المقاس المختار', max_length=100),
        ),
    ]
