# Generated by Django 5.2.8 on 2025-12-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_size_name'),
        ('products', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant', 'unit_type', 'size_name')},
        ),
    ]
