# Generated by Django 5.2.8 on 2025-12-27 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'تم الإلغاء')], default='pending', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('piece', 'قطعة'), ('carton', 'كرتونة')], default='carton', max_length=10)),
                ('variant_info', models.CharField(blank=True, help_text='معلومات النمط وقت الطلب', max_length=200)),
                ('variant_pcs_carton', models.PositiveIntegerField(blank=True, help_text='عدد القطع في الكرتونة وقت الطلب', null=True)),
                ('color_name', models.CharField(blank=True, help_text='اسم اللون وقت الطلب', max_length=100)),
                ('size_name', models.CharField(blank=True, help_text='اسم الطول/المقاس وقت الطلب', max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
        ),
    ]
