# Generated by Django 5.2.8 on 2025-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, help_text='اسم اللون وقت الطلب', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, help_text='اسم الطول/المقاس وقت الطلب', max_length=100),
        ),
    ]
