# Generated by Django 5.2.8 on 2026-01-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'تفاصيل الطلب', 'verbose_name_plural': 'تفاصيل الطلبات'},
        ),
    ]
