# Generated by Django 5.2.8 on 2025-12-29 09:18

import django.db.models.deletion
import utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='category-images')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
                ('hex_code', models.CharField(help_text='مثال: #FF0000 للأحمر', max_length=7, verbose_name='كود اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لون',
                'verbose_name_plural': 'الألوان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المقاس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pcs_carton', models.PositiveIntegerField(default=24)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='product-image')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product')),
            ],
            options={
                'verbose_name': 'صورة إضافية',
                'verbose_name_plural': 'صور إضافية',
                'ordering': ['order', 'created_at'],
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('color', 'اللون')], max_length=20)),
                ('name', models.CharField(help_text='اسم النمط الكامل', max_length=200)),
                ('code', models.CharField(blank=True, help_text='كود/SKU خاص بالنمط', max_length=50, null=True, unique=True)),
                ('pcs_carton', models.PositiveIntegerField(default=24, help_text='عدد القطع في الكرتونة لهذا النمط')),
                ('image', models.ImageField(blank=True, help_text='صورة خاصة بالنمط', null=True, upload_to='variant-images')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, help_text='اللون الخاص بهذا النمط (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.color', verbose_name='اللون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('sizes', models.ManyToManyField(blank=True, help_text='الأطوال/المقاسات المتاحة لهذا النمط (اختياري)', related_name='variants', to='products.size', verbose_name='الأطوال المتاحة')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['variant_type'],
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variants/', verbose_name='الصورة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'صورة نمط',
                'verbose_name_plural': 'صور الأنماط',
                'ordering': ['order', 'created_at'],
            },
            bases=(utils.image_utils.ImageCompressionMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='products_pr_categor_546c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_1a7436_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_available'], name='products_pr_product_dfcfbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'code')},
        ),
    ]
