# Generated by Django 5.2.8 on 2026-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='length_label',
            field=models.CharField(blank=True, help_text='مثال: مقاس السلك، طول الصابع', max_length=50, null=True, verbose_name='نوع الطول'),
        ),
    ]
