# Generated by Django 5.2.8 on 2026-01-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_length_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['variant_type'], 'verbose_name': 'نمط المنتج', 'verbose_name_plural': 'أنماط المنتجات'},
        ),
    ]
