# Generated by Django 5.2.8 on 2025-12-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimages_options_productimages_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
                ('hex_code', models.CharField(help_text='مثال: #FF0000 للأحمر', max_length=7, verbose_name='كود اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لون',
                'verbose_name_plural': 'الألوان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المقاس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, help_text='اللون الخاص بهذا النمط (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.color', verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sizes',
            field=models.ManyToManyField(blank=True, help_text='الأطوال/المقاسات المتاحة لهذا النمط (اختياري)', related_name='variants', to='products.size', verbose_name='الأطوال المتاحة'),
        ),
    ]
