# Generated by Django 5.2.8 on 2025-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_size_productvariant_color_productvariant_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcs_carton',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_1a7436_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_available'], name='products_pr_product_dfcfbe_idx'),
        ),
    ]
