# Generated by Django 5.2.8 on 2026-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_order_color_order_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
