# Generated by Django 5.2.8 on 2026-02-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_order_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['order'], 'verbose_name': 'لون', 'verbose_name_plural': 'الألوان'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
