# Generated by Django 5.2.8 on 2026-02-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_color_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order'], 'verbose_name': 'نمط المنتج', 'verbose_name_plural': 'أنماط المنتجات'},
        ),
    ]
