# Generated by Django 5.2.8 on 2026-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variantattribute_alter_variantimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variantimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'صورة نمط', 'verbose_name_plural': 'صور الأنماط'},
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='hex_code',
            field=models.CharField(blank=True, help_text='يستخدم فقط لو كانت الخاصية لون', max_length=7, null=True),
        ),
    ]
